teleop:
  regular:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [8]
    axis_mappings:
      -
        axis: 1
        target: linear.z
        scale: 0.5
      -
        axis: 0
        target: angular.z
        scale: 0.3
      -
        axis: 3
        target: linear.x
        scale: 0.3
      -
        axis: 2
        target: linear.y
        scale: 0.3

  turbo:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [10]
    axis_mappings:
      -
        axis: 1
        target: linear.z
        scale: 0.8
      -
        axis: 0
        target: angular.z
        scale: 0.5
      -
        axis: 3
        target: linear.x
        scale: 0.5
      -
        axis: 2
        target: linear.y
        scale: 0.5        